Add the scripts for the modal
Bestbynature/portfolio pull request #17
Opened 2023-03-06 15:26 UTC by Bestbynature

⚡ Features include:

- When the user clicks (or taps) the hamburger button, the mobile menu appears.
- When the user clicks (or taps) the close (X) button, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.

2023-03-06 19:28 UTC, omarsalem7 requested changes
Hi @Bestbynature 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/j7vckgz15cAYmxatzB/giphy.gif)

## Highlights
- Pop modal open and close properly ✔️
- The Pull Request has a proper title and description. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-06 19:28 UTC, omarsalem7 commented on index.js
> +}
- [ ] Kindly consider making the modal take the height of the screen by changing the height of the modal to `100vh` at [this line](https://github.com/Bestbynature/portfolio/blob/15a22bc86d493c35a0523641962692d8678559bd/styles.css#L87)
- [ ] Also consider sticking to the design by using the correct font size and also make sure to put the close icon in the proper position like the Figma design to make your design identical to Figma

| Your design  | Figma design|
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/53402600/223209571-46787eaf-3621-4b73-9bbc-30173a1b18b5.png) | ![image](https://user-images.githubusercontent.com/53402600/223210388-c93c741b-6bdc-4fca-ab81-829a6660a039.png) |

2023-03-06 20:23 UTC, levy002 requested changes
## Hello @Bestbynature   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] As requested by the previous reviewer, kindly make sure your mobile menu covers the whole screen height and make sure even if we scroll down the mobile menu will still cover the whole weight of the visible screen.

   - ### APP BEHAVIOUR 
   ![chrome-capture-2023-2-6](https://user-images.githubusercontent.com/87197412/223220434-41fbeb2b-d32b-4e60-9392-311761421b21.gif)
  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-06 20:29 UTC, Bestbynature commented
@levy002 , Thank you for the point you raised. But as he advised, I changed the height from 95vh to 100vh. Are you suggesting i increase it from 100 to something more??

2023-03-07 03:05 UTC, nicupop729 reviewed
Hello @Bestbynature and @melybee-07  👋,

_This is an additional review as a result of the second opinion request._

Kudos for the good project you built here!

Because what was asked by the first reviewer was implemented, correctly would have been that the second reviewer to approve the CRR. 
He still asked it because the feature for was not still working. More refactoring is required than to just add 100vh to the container. 
@omarsalem7 should have research a bit more the code in order to give an accurate advice.   

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approve right away :)

Keep rocking 🚀!

2023-03-07 03:23 UTC, Shedrack-Sunday approved these changes
Hi @Bestbynature 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)


# Highlights
- No linter errors ✔️
- Good implementations ✔️


## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


__check the comments for details

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-07 03:39 UTC, merged